<#import "template.ftl" as layout>
<@layout.registrationLayout displayMessage=!messagesPerField.existsError('totp') showMarketingPanel=false; section>

  <#if section = "header">
    Set up authenticator
  <#elseif section = "subtitle">
    Secure your account with two-factor authentication
  <#elseif section = "form">

    <div class="ms-otp-info">
      <ol>
        <li>Install an authenticator app on your phone (e.g. Google Authenticator, Authy, or Microsoft Authenticator).</li>
        <li>Scan the QR code below or manually enter the secret key.</li>
        <li>Enter the 6-digit code generated by the app to verify setup.</li>
      </ol>
    </div>

    <#-- QR code -->
    <div class="ms-qr-code">
      <img src="data:image/png;base64,${totp.totpSecretQrCode}" alt="QR code">
    </div>

    <#-- Manual secret key -->
    <div class="ms-totp-secret">
      <p style="font-size:13px;color:#888888;margin-bottom:8px;">Or enter this key manually:</p>
      <code>${totp.totpSecretEncoded}</code>
    </div>

    <form action="${url.loginAction}" method="post">

      <#-- Hidden fields -->
      <input type="hidden" id="totpSecret" name="totpSecret" value="${totp.totpSecret}">
      <#if mode??>
        <input type="hidden" id="mode" name="mode" value="${mode}">
      </#if>

      <#-- Device name -->
      <div class="ms-form-group">
        <label for="userLabel">${msg("loginTotpDeviceName")}</label>
        <input id="userLabel" name="userLabel" type="text" class="ms-input" autocomplete="off" placeholder="e.g. My Phone">
      </div>

      <#-- OTP code -->
      <div class="ms-form-group">
        <label for="totp">${msg("authenticatorCode")} <span class="ms-required">*</span></label>
        <input id="totp" name="totp" type="text" class="ms-input <#if messagesPerField.existsError('totp')>ms-input--error</#if>" autocomplete="one-time-code" autofocus inputmode="numeric" pattern="[0-9]*">
        <#if messagesPerField.existsError('totp')>
          <div class="ms-alert ms-alert--error" style="margin-top:6px;margin-bottom:0">${kcSanitize(messagesPerField.getFirstError('totp'))?no_esc}</div>
        </#if>
      </div>

      <#-- Submit -->
      <div class="ms-form-actions">
        <button type="submit" class="ms-btn ms-btn--primary">${msg("doSubmit")}</button>
      </div>

    </form>

  </#if>

</@layout.registrationLayout>
